name: Build and Deploy theme on push

on:
  push
    
jobs:
  push-shopify-theme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        
      - name: Push Shopify theme
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_PASSWORD }}
          SHOPIFY_FLAG_STORE: ${{ vars.SHOPIFY_STORE }}
          SHOPIFY_FLAG_THEME_ID: ${{ vars.THEME_ID }}
          # SHOPIFY_FLAG_PATH: src
        run: npx @shopify/cli@3.83.3 theme push

